export const ACTIVITY_MOCK = [
  {
    id: 1,
    title: "City Tour",
    price: 100,
    currency: "$",
    rating: 4,
    specialOffer: false,
    supplierId: 100,
    supplier: {
      id: 100,
      name: "Jackie Chan",
      address: "789 Main St",
      zip: "10000",
      city: "Hong Kong",
      country: "China",
    },
  },
  {
    id: 2,
    title: "Museum Ticket",
    price: 20,
    currency: "¥",
    rating: 4.5,
    specialOffer: true,
    supplierId: 200,
    supplier: {
      id: 200,
      name: "Bruce Lee",
      address: "123 Long Rd",
      zip: "20000",
      city: "San Francisco",
      country: "USA",
    },
  },
  {
    id: 3,
    title: "Nature Tour",
    price: 150,
    currency: "€",
    rating: 5,
    specialOffer: true,
    supplierId: 100,
    supplier: {
      id: 100,
      name: "Jackie Chan",
      address: "789 Main St",
      zip: "10000",
      city: "Hong Kong",
      country: "China",
    },
  },
];
