services:
  node-backend:
    build:
      context: .
      dockerfile: ./node-backend/Dockerfile
    ports:
      - "8080:8080"

  react-frontend:
    build:
      context: .
      dockerfile: ./react-frontend/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - node-backend
