services:
  node-backend:
    build:
      context: ./node-backend
    ports:
      - "8080:8080"

  react-frontend:
    build:
      context: ./react-frontend
    ports:
      - "8081:4173"
    depends_on:
      - node-backend
